workspace:
  base: /build

pipeline:
  build:
    image: trion/ng-cli
    commands:
      - npm install
      - np build --aot
      - tar -xcvf app.tar.gz /build/dist

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /build/target
    commands:
      - ls /build
      - ls /build/dist
    ttl: 7
    when:
      branch: [ complete ]
      event: push
    
  deploy:
    image: plugins/docker
    dockerfile: Dockerfile
    mount:
      - /build/dist
    repo: hikaruright/spring-test
    tags:
      - latest
      - 1.0.0
      - 0.0.1
    when:
      branch: [ complete ]
      event: push
