workspace:
  base: /build

pipeline:
  build:
    image: johnpapa/angular-cli
    commands:
      # - npm install -g @angular/cli
      # - npm install
      # - ng build --aot
      - tar -zcvf app.tar.gz /build/dist/bookmanagement-angular/*
      - mv ./app.tar.gz /build
      # - rm -rf node_modules
      # - cp /build/dist/bookmanagement-angular /build
    mount:
      - /build/dist
    # when:
    #   branch: [ master ]
    #   event: push

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    commands:
      - ls /build
    ttl: 7
    # when:
    #   branch: [ master ]
    #   event: push
  
  docker-build:
    image: plugins/docker
    dockerfile: Dockerfile
    mount:
      - /build
    settings:
      repo: hikaruright/bookmanagement-angular
      username: hikaruright
      password: solxyz001
    tags:
      - latest
      - 1.0.0
      - 0.0.1
    # when:
    #   branch: [ master ]
    #   event: push